Add a side container to glusterfs handling cron jobs managed by snapshot scheduler.

diff --git a/deploy/asd-azure-kube-templates/glusterfs-daemonset.yaml b/deploy/asd-azure-kube-templates/glusterfs-daemonset.yaml
--- a/deploy/asd-azure-kube-templates/glusterfs-daemonset.yaml
+++ b/deploy/asd-azure-kube-templates/glusterfs-daemonset.yaml
@@ -71,6 +71,45 @@ spec:
           periodSeconds: 25
           successThreshold: 1
           failureThreshold: 15
+      - image: gluster/gluster-centos:latest
+        imagePullPolicy: IfNotPresent
+        name: glusterfs-snapshot-scheduler
+        command: ["/bin/sh"]
+        args: ["/opt/snaphot-scheduler/bin/entrypoint.sh"]
+        securityContext:
+          capabilities: {}
+          privileged: true
+        readinessProbe:
+          initialDelaySeconds: 40
+          timeoutSeconds: 15
+          exec:
+            command:
+            - /bin/bash
+            - /opt/snaphot-scheduler/bin/health.sh
+          periodSeconds: 25
+          successThreshold: 1
+          failureThreshold: 15
+        livenessProbe:
+          initialDelaySeconds: 40
+          timeoutSeconds: 15
+          exec:
+            command:
+            - /bin/bash
+            - /opt/snaphot-scheduler/bin/health.sh
+          periodSeconds: 25
+          successThreshold: 1
+          failureThreshold: 15
+        lifecycle:
+          postStart:
+            exec:
+              command: ["/bin/sh", "-c", "[[ -e /run/glusterd.socket ]] || ln -s /tmp/run/glusterd.socket /run/glusterd.socket"]
+        volumeMounts:
+        - name: glusterfs-run
+          mountPath: "/tmp/run"
+        - name: glusterfs-snapshot-scheduler-run
+          mountPath: "/run"
+        - name: glusterfs-snapshot-scheduler-entrypoint
+          mountPath: /opt/snaphot-scheduler/bin
       volumes:
       - name: glusterfs-heketi
         hostPath:
@@ -100,3 +139,54 @@ spec:
       - name: glusterfs-ssl
         hostPath:
           path: "/etc/ssl"
+      - name: glusterfs-snapshot-scheduler-run
+      - name: glusterfs-snapshot-scheduler-entrypoint
+        configMap:
+          name: glusterfs-snapshot-scheduler-script
+          items:
+            - key: entrypoint
+              path: entrypoint.sh
+            - key: health
+              path: health.sh
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: glusterfs-snapshot-scheduler-script
+data:
+  entrypoint: |-
+    #!/bin/sh
+    sleep 30
+    while
+      echo -n "Initializing snapshot_scheduler ... "
+      snap_scheduler.py init > /dev/null 2>&1
+      code=$?
+      [[ $code == 0 ]] \
+        && echo "ok" \
+        || echo "failed"
+      [[ $code == 3 || $code == 4 ]] \
+        && echo -n "Mounting glusterfs shared storage ... " \
+        && mkdir -p /run/gluster/shared_storage \
+        && mount.glusterfs $(hostname):/gluster_shared_storage /run/gluster/shared_storage > /dev/null 2>&1 \
+        && echo "ok"
+      [[ $code != 0 && $code != 3 && $code != 4 ]] && echo "Error code unknown: $code"
+      [[ $code == 0 ]] \
+        && echo -n "Enabling snapshot scheduling ... " \
+        && snap_scheduler.py enable > /dev/null 2>&1; code_enable=$? \
+        && [[ $code_enable == 0 || $code_enable == 8 ]] \
+        && echo "ok" \
+        && break \
+        || [[ $code == 0 ]] \
+        && echo "failed, exiting with error" \
+        && exit 1
+      sleep 5
+      [[ $code != 0 || $(gluster peer status > /dev/null 2>&1; echo $?) != 0 ]]
+    do :;  done
+    /usr/sbin/crond -n
+  health: |-
+    #!/bin/bash
+    gluster peer status > /dev/null \
+      && pgrep --pidfile /run/crond.pid > /dev/null 2>&1 \
+      && snap_scheduler.py status > /dev/null; code=$?; [[ $code == 0 || $code == 5 ]] \
+      || (! gluster volume list | grep gluster_shared_storage > /dev/null \
+      && ! pgrep --pidfile /run/crond.pid > /dev/null 2>&1)
